Выполнено ДЗ Методы
rom064/Homework11 pull request #1
Opened 2023-02-26 15:32 UTC by rom064

Проверьте ДЗ Методы

2023-02-26 18:09 UTC, alekseykoshelev requested changes

2023-02-26 18:09 UTC, alekseykoshelev commented on src/Main.java
> +    public static void operatingSystem(int client_OS, int DeviceYear) {
Переменные называем с маленькой буквы и используем `camelCase`

2023-02-26 18:09 UTC, alekseykoshelev commented on src/Main.java
> +    public static void delivery(int deliveryDistance) {
Тут нужно чтобы метод возвращал значение, а именно, количество дней доставки. Вывод внутри этого метода делать не нужно, вывод можно сделать внутри метода `task3`.

2023-03-01 15:49 UTC, rom064 commented on src/Main.java
> +    public static void operatingSystem(int client_OS, int DeviceYear) {
здесь нет переменных с большой буквы..

2023-03-01 18:53 UTC, merged